// Canonical public offer architecture.
// Source: Devonshire_Offer_Architecture_Canonical.md (v1.4, July 20, 2026).
// Keep website copy, analytics values, and CRM-facing labels aligned to these values.

export const OFFERS = Object.freeze({
  executionRiskReview: Object.freeze({
    key: "execution_risk_review",
    name: "Devonshire Execution Risk Review",
    shortName: "Execution Risk Review",
    category: "Operator-led operational diligence",
    price: "From $20,000",
    timing: "2–3 weeks",
    primaryDeliverable: "Execution Risk Memo",
    buyerQuestion: "What operating risks are we underestimating before we own this business?",
    purpose: "Pressure-test whether the target's operating infrastructure can deliver the investment thesis under new ownership.",
    homepageDeliverables: Object.freeze([
      "Execution Risk Memo + Execution Risk Scorecard",
      "Targeted Evidence Request List",
      "Day-1 Critical Path + Day-1 to Day-100 Priority Map",
      "Live Sponsor Readout",
    ]),
    deliverables: Object.freeze([
      "Execution Risk Memo",
      "Execution Risk Scorecard",
      "Targeted Evidence Request List",
      "Day-1 Critical Path",
      "Day-1 to Day-100 Priority Map",
      "Live Sponsor Readout",
    ]),
  }),
  operatingDesign: Object.freeze({
    key: "100_day_operating_design",
    name: "100-Day Operating Design",
    category: "100-day operating planning",
    price: "From $30,000",
    timing: "Scoped to the mandate",
    primaryDeliverable: "100-Day Operating Playbook",
    buyerQuestion: "What must management and the sponsor install, in what sequence, to establish operating control during the first 100 days?",
    purpose: "Convert known operating priorities into a sequenced, owned, measurable execution architecture.",
    deliverables: Object.freeze([
      "100-Day Operating Playbook",
      "Initiative and Sequencing Map",
      "Ownership and Decision Map",
      "KPI Architecture",
      "Operating Cadence and Sponsor Visibility Plan",
    ]),
  }),
  diligenceToExecution: Object.freeze({
    key: "diligence_to_execution_mandate",
    name: "Diligence-to-Execution Mandate",
    category: "Operational diligence and execution planning",
    price: "From $45,000",
    timing: "LOI → Day 100",
    primaryDeliverable: "Execution Risk Memo + 100-Day Operating Playbook",
    buyerQuestion: "How do we carry the operating risks identified before close directly into Day-1 and 100-day execution without re-learning or losing ownership?",
    purpose: "Carry pre-close operating findings directly into a sequenced and owned 100-day operating plan.",
    integrationNote: "One continuous mandate from diligence through operating design, with overlapping artifacts consolidated and ownership preserved across the transition.",
    homepageDeliverables: Object.freeze([
      "Execution Risk Memo + Execution Risk Scorecard",
      "Targeted Evidence Request List + Day-1 Readiness Plan",
      "100-Day Operating Playbook",
      "Ownership, KPI, cadence + Sponsor Progress Architecture",
      "Live Sponsor Readout",
    ]),
    deliverables: Object.freeze([
      "Execution Risk Memo",
      "Execution Risk Scorecard",
      "Targeted Evidence Request List",
      "Day-1 Readiness Plan",
      "100-Day Operating Playbook",
      "Ownership and Accountability Map",
      "KPI and Operating Cadence Architecture",
      "Sponsor Progress Architecture",
      "Live Sponsor Readout",
    ]),
  }),
  operatingControlSprint: Object.freeze({
    key: "operating_control_sprint",
    name: "Operating Control Sprint",
    category: "Embedded operating implementation",
    price: "From $25,000",
    timing: "2–6 weeks",
    primaryDeliverable: "Installed Operating Control + Capability Transfer Pack",
    buyerQuestion: "Which operating control must be installed now to prevent drift, firefighting, or loss of sponsor visibility?",
    purpose: "Install one defined operating capability or control and transfer ownership to management.",
    homepageDeliverables: Object.freeze([
      "Installed Operating Control or Capability",
      "Governance and Ownership Map",
      "KPI, Risk, or Control Pack",
      "Implementation Record + Open Action Register",
      "Capability Transfer Pack",
    ]),
    deliverables: Object.freeze([
      "Installed Operating Control or Capability",
      "Governance and Ownership Map",
      "KPI, Risk, or Control Pack",
      "Implementation Record and Open Action Register",
      "Capability Transfer Pack",
    ]),
  }),
  postCloseControlTower: Object.freeze({
    key: "post_close_control_tower",
    name: "Post-Close Control Tower",
    category: "Post-close execution governance",
    price: "From $10,000/month",
    timing: "3-month initial term",
    primaryDeliverable: "Sponsor Operating Pack + Control Tower Dashboard",
    buyerQuestion: "How does the sponsor maintain visibility, management accountability, and execution cadence without adding permanent operating-partner headcount?",
    purpose: "Maintain the cadence, visibility, escalation discipline, and decision infrastructure required to prevent post-close drift.",
    homepageDeliverables: Object.freeze([
      "Sponsor Operating Pack + Control Tower Dashboard",
      "Decision and Action Register + Operating Risk Watchlist",
      "Monthly Board Readiness Pack",
      "Capability Transfer + Institutional Knowledge Record",
      "Weekly Operating Review + Escalation Governance",
    ]),
    deliverables: Object.freeze([
      "Sponsor Operating Pack",
      "Control Tower Dashboard",
      "Decision and Action Register",
      "Operating Risk Watchlist",
      "Monthly Board Readiness Pack",
      "Capability Transfer and Institutional Knowledge Record",
      "Weekly Operating Review",
      "Escalation Governance",
    ]),
  }),
});

export const DELIVERABLE_KEYS = Object.freeze({
  executionRiskMemo: "execution_risk_memo",
  executionRiskScorecard: "execution_risk_scorecard",
  targetedEvidenceRequestList: "targeted_evidence_request_list",
  day1CriticalPath: "day_1_critical_path",
  day1ToDay100PriorityMap: "day_1_to_day_100_priority_map",
  sponsorReadout: "sponsor_readout",
  operatingPlaybook: "100_day_operating_playbook",
  initiativeSequencingMap: "initiative_sequencing_map",
  ownershipDecisionMap: "ownership_decision_map",
  kpiArchitecture: "kpi_architecture",
  operatingCadenceSponsorVisibilityPlan: "operating_cadence_sponsor_visibility_plan",
  day1ReadinessPlan: "day_1_readiness_plan",
  ownershipAccountabilityMap: "ownership_accountability_map",
  kpiOperatingCadenceArchitecture: "kpi_operating_cadence_architecture",
  sponsorProgressArchitecture: "sponsor_progress_architecture",
  installedOperatingControl: "installed_operating_control",
  governanceOwnershipMap: "governance_ownership_map",
  kpiRiskControlPack: "kpi_risk_control_pack",
  implementationOpenActionRegister: "implementation_open_action_register",
  capabilityTransferPack: "capability_transfer_pack",
  sponsorOperatingPack: "sponsor_operating_pack",
  controlTowerDashboard: "control_tower_dashboard",
  decisionActionRegister: "decision_action_register",
  operatingRiskWatchlist: "operating_risk_watchlist",
  monthlyBoardReadinessPack: "monthly_board_readiness_pack",
  capabilityTransferInstitutionalKnowledgeRecord: "capability_transfer_institutional_knowledge_record",
});
